jobs:
- job: build_onnxruntime_web
  pool: Linux-CPU-2019
  strategy:
    maxParallel: 2
    matrix:
      'debug':
        BuildConfig: 'Debug'
      'release':
        BuildConfig: 'Release'

  timeoutInMinutes: 30
  workspace:
    clean: all
  steps:
  - checkout: self
    submodules: false
  - script: |
     git submodule sync -- cmake/external/onnx
     git submodule update --init -- cmake/external/onnx
    workingDirectory: '$(Build.SourcesDirectory)'
    displayName: 'Checkout submodule onnx'
  - task: NodeTool@0
    inputs:
      versionSpec: '14.x'
  - script: |
     npm ci
    workingDirectory: '$(Build.SourcesDirectory)/js'
    displayName: 'npm ci /js/'
  - script: |
     npm ci
    workingDirectory: '$(Build.SourcesDirectory)/js/common'
    displayName: 'npm ci /js/common/'
  - script: |
     npm ci
    workingDirectory: '$(Build.SourcesDirectory)/js/web'
    displayName: 'npm ci /js/web/'
  - script: |
     npm run pull:wasm
    workingDirectory: '$(Build.SourcesDirectory)/js/web'
    displayName: 'Binplace js files'
  - script: |
     npm run build
    workingDirectory: '$(Build.SourcesDirectory)/js/web'
    displayName: 'Build ort-web'
  - task: BrowserStackConfig@0
    inputs:
      BrowserStackServiceEndPoint: 'BrowserStack Connection'
      browserstackLocal: true
    displayName: 'BrowserStack configuration setup'
    timeoutInMinutes: 20
    condition: and(succeeded(), eq(variables['BuildConfig'], 'Release'))
  - script: |
      export ONNXJS_TEST_BS_BROWSERS=BS_ANDROID_11_Pixel_5
      npm test -- suite0 --env=bs --wasm-init-timeout=30000 --file-cache
    workingDirectory: '$(Build.SourcesDirectory)/js/web'
    displayName: 'npm test (Suite0, BS_ANDROID_*)'
    condition: eq(variables['BuildConfig'], 'Release')
    env:
      BROWSERSTACK_ACCESS_KEY: $(BROWSERSTACK_ACCESS_KEY)
      BROWSERSTACK_USERNAME: $(BROWSERSTACK_USERNAME)
  - script: |
      export ONNXJS_TEST_BS_BROWSERS=BS_IOS_14_iPhoneXS
      npm test -- suite0 --env=bs --wasm-init-timeout=30000 --file-cache --backend=wasm
    workingDirectory: '$(Build.SourcesDirectory)/js/web'
    displayName: 'npm test (Suite0, BS_IOS_*)'
    condition: eq(variables['BuildConfig'], 'Release')
    env:
      BROWSERSTACK_ACCESS_KEY: $(BROWSERSTACK_ACCESS_KEY)
      BROWSERSTACK_USERNAME: $(BROWSERSTACK_USERNAME)
  - task: BrowserStackStopLocal@0
  - task: BrowserStackResults@0
    displayName: 'BrowserStack results'
    continueOnError: true
    timeoutInMinutes: 10
    condition: eq(variables['BuildConfig'], 'Release')
  - task: mspremier.PostBuildCleanup.PostBuildCleanup-task.PostBuildCleanup@3
    displayName: 'Clean Agent Directories'
    condition: always()
